name: Build and deploy to kubeflow pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: malikrohit16
          password: dckr_pat_mN-_7AL1Ulg64-YM3FB82QFzY2U
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: malikrohit16
          password: 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

      - name: Build and push container image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: docker.pkg.github.com/malikrohit16/kubeflow_ci-cd/train:latest
          context: .
          file: ./Dockerfile

      - name: Deploy to kubeflow Pipelines
        uses: NikeNano/kubeflow-pipeline-deploy-action@v0.2
        with:
          host: http://10.64.140.43/?ns=admin
          namespace: admin
          name: train-pipeline
          image: docker.pkg.github.com/malikrohit16/kubeflow_ci-cd/train:latest
