name: Build and deploy to kubeflow pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t localhost:5000/image1 .

      - name: push image to docker registry
        run: |
          echo registrypassword | docker login --username rohit16 --password-stdin localhost:5000
          docker push localhost:5000/image1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: malikrohit16
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: malikrohit16
      #     password: ${{ secrets.G_TOKEN }}

      # - name: Build and push container image
      #   id: docker_build
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: docker.pkg.github.com/malikrohit16/kubeflow_ci-cd/train:latest
      #     context: .
      #     file: ./Dockerfile

      # - name: Deploy to kubeflow Pipelines
      #   uses: f6wbl6/kubeflow-pipelines-deploy-action@master
      #   with:
      #     host: http://10.64.140.43/?ns=admin
      #     namespace: admin
      #     name: train-pipeline
      #     image: docker.pkg.github.com/malikrohit16/kubeflow_ci-cd/train:latest

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t localhost:5000/kubeflow_image_test:latest .
      #     docker push localhost:5000/kubeflow_image_test:latest

      # - name: Run Kubeflow pipeline
      #   env:
      #     KFP_ENDPOINT: http://10.64.140.43/?ns=admin
      #     KFP_AUTH_TOKEN: ${{ secrets.KFP_AUTH_TOKEN }}
      #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
      #   run: |
      #     python train.py
