name: Build and deploy to kubeflow pipeline

on:
  push :
    branches:
      - main

jobs:
  build-and-deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push container image
      id: docker_build
      uses: docker/build-push-actions@v2
      with:
        push: true
        tags: docker.pkg.github.com/malikrohit16/kubeflow_ci-cd/train:latest
        context: .
        file: ./Dockerfile

    - name: Deploy to kubeflow Pipelines
      uses: d-kuro/kubeflow-pipeline-deploy-action@v0.2
      with:
        host: http://10.64.140.43/?ns=admin
        namespace: admin
        name: train-pipeline
        image: docker.pkg.github.com/malikrohit16/kubeflow_ci-cd/train:latest